name: .NET 6

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Build solution and generate NuGet package
      run: |
        cd src\DotNetEd.CoreAdmin
        dotnet pack -c Release -o out  
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
    - name: Push generated package to Nuget
      run: nuget push src\DotNetEd.CoreAdmin\out\*.nupkg -SkipDuplicate -NoSymbols -Source https://api.nuget.org/v3/index.json

